export const ADD_STORY = 'ADD_STORY';
export const REMOVE_STORY = 'REMOVE_STORY';
export const COMPLETE_STORY = 'COMPLETE_STORY';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_STORY';
export const COMPLETE_COMMENT = 'COMPLETE_COMMENT';

